name: jaguar_gzip
description: Gzip compressor interceptors for Jaguar
version: 0.5.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_gzip

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar: ^0.6.5

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_static_file: '>=0.5.0 <0.6.0'
